
services:
  blogs_app:
    build: ./blogs/.         
    ports:
      - "8080:8080"
    environment:
      DB_NAME: blogs
      DB_HOST: blogs_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DJANGO_SECRET_KEY: dummysecretkey
      CELERY_BROKER_URL: amqp://kevinmq:kevinmq@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      blogs_db:
        condition: service_healthy
    networks:
    - app_net
  blogs_db:
    image: postgres
    environment:
      POSTGRES_DB: blogs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto AMQP (para Celery)
      - "15672:15672" # UI Web para RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: kevinmq
      RABBITMQ_DEFAULT_PASS: kevinmq
    networks:
      - app_net
  celery_worker:
    build: ./worker/.
    command: celery -A worker worker --loglevel=info
    environment:
      DB_NAME: blogs
      DB_HOST: blogs_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      CELERY_BROKER_URL: amqp://kevinmq:kevinmq@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - blogs_db
    networks:
      - app_net
networks:
  app_net: